# Generated by Django 4.1 on 2023-02-17 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eduexperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('school', models.CharField(max_length=255)),
                ('edulevel', models.CharField(max_length=255)),
                ('starttime', models.CharField(max_length=255)),
                ('endtime', models.CharField(max_length=255)),
                ('major', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'eduexperience',
            },
        ),
        migrations.CreateModel(
            name='jobexperience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unitname', models.CharField(max_length=255)),
                ('unitaddress', models.CharField(max_length=255)),
                ('starttime', models.CharField(max_length=255)),
                ('endtime', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('typeJobExp', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'jobexperience',
            },
        ),
        migrations.CreateModel(
            name='authentication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('cardtype', models.CharField(max_length=255)),
                ('cardnum', models.CharField(max_length=255)),
                ('currentunit', models.CharField(max_length=255)),
                ('persontype', models.CharField(max_length=255)),
                ('eduexperience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urequest.eduexperience')),
                ('jobexperience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urequest.jobexperience')),
            ],
            options={
                'db_table': 'authentication',
            },
        ),
    ]
