# Generated by Django 4.1 on 2023-02-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urequest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='eduexperience',
        ),
        migrations.RemoveField(
            model_name='authentication',
            name='jobexperience',
        ),
        migrations.AddField(
            model_name='eduexperience',
            name='auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='urequest.authentication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='urequest.authentication'),
            preserve_default=False,
        ),
    ]
