# Generated by Django 4.1 on 2023-02-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urequest', '0002_remove_authentication_eduexperience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='persontype',
        ),
        migrations.CreateModel(
            name='persontype',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urequest.authentication')),
            ],
            options={
                'db_table': 'persontype',
            },
        ),
    ]
