# Generated by Django 3.2.8 on 2023-02-13 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_career'),
    ]

    operations = [
        migrations.CreateModel(
            name='tech',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('level', models.CharField(max_length=255)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tech',
            },
        ),
        migrations.RenameModel(
            old_name='police',
            new_name='policy',
        ),
    ]
