# Generated by Django 4.1 on 2023-02-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20230214_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='time',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='unit',
        ),
        migrations.AddField(
            model_name='career',
            name='companyinfo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='companyname',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='contactor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='career',
            name='jobinfo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='career',
            name='salary',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
