# Generated by Django 4.1 on 2023-02-15 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_policy_time_remove_policy_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='policy',
            name='unit',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
