# Generated by Django 4.1 on 2023-02-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_policy_time_policy_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.CharField(blank=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
