# Generated by Django 4.1 on 2023-02-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_career_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='wxUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('hometown', models.CharField(blank=True, max_length=30)),
                ('place', models.CharField(blank=True, max_length=30)),
                ('trade', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=30)),
                ('salary', models.CharField(blank=True, max_length=30)),
                ('education', models.CharField(blank=True, max_length=30)),
                ('school', models.CharField(blank=True, max_length=30)),
                ('positionaltitle', models.CharField(blank=True, max_length=30)),
                ('countryposition', models.CharField(blank=True, max_length=30)),
                ('field', models.CharField(blank=True, max_length=30)),
                ('majorate', models.CharField(blank=True, max_length=30)),
                ('aboard', models.CharField(blank=True, max_length=30)),
                ('experience', models.CharField(blank=True, max_length=30)),
                ('experiences', models.CharField(blank=True, max_length=30)),
                ('honors', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'wxUser',
            },
        ),
    ]
