# Generated by Django 4.1 on 2023-02-15 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_wxuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wxuser',
            old_name='aboard',
            new_name='abroad',
        ),
    ]
