# Generated by Django 4.1 on 2023-02-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_rename_aboard_wxuser_abroad'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='avatarUrl',
            field=models.URLField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='career',
            name='email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
