# Generated by Django 4.1 on 2023-02-15 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_wxuser_avatarurl_alter_career_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(-1, 'comment'), (0, 'policy'), (1, 'job')], default=-1)),
                ('foreignid', models.IntegerField()),
                ('commenterid', models.IntegerField()),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.AlterField(
            model_name='career',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tech',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
