# Generated by Django 4.1 on 2023-02-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_comment_alter_career_id_alter_policy_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='password',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
