# Generated by Django 4.1 on 2023-02-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_wxuser_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxuser',
            name='level',
            field=models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
