# Generated by Django 4.1 on 2023-02-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_wxuser_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='superid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='supertype',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
