# Generated by Django 4.1 on 2023-02-16 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_comment_isread_comment_superid_comment_supertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='isRead',
            field=models.BooleanField(default=True),
        ),
    ]
