# Generated by Django 4.1 on 2023-02-16 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_comment_isread'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='foreignid',
            new_name='preid',
        ),
        migrations.AddField(
            model_name='comment',
            name='isReply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
