# Generated by Django 4.1 on 2023-02-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_alter_wxuser_avatarurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wxuser',
            name='level',
            field=models.CharField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F')], default=6, max_length=2),
        ),
    ]
