# Generated by Django 4.1 on 2023-02-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_alter_wxuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='companyinfo',
            field=models.TextField(max_length=255),
        ),
    ]
