# Generated by Django 4.1 on 2023-02-17 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0019_tech_companyname_tech_email_tech_introduce_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='introduce',
            field=models.TextField(blank=True),
        ),
    ]
