# Generated by Django 4.1 on 2023-02-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_alter_tech_introduce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='isRead',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wxuser',
            name='level',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F')], default=6),
        ),
    ]
