# Generated by Django 4.1 on 2023-02-16 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_ecard'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('name', models.CharField(max_length=255)),
                ('master', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('photo', models.URLField(max_length=255)),
                ('website', models.URLField(max_length=255)),
                ('introduce', models.TextField()),
                ('project', models.TextField()),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='government',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'government',
            },
        ),
        migrations.CreateModel(
            name='governmentContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contacttype', models.CharField(max_length=255)),
                ('governmentid', models.IntegerField()),
                ('contactor', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'governmentContact',
            },
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unique', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('photo', models.CharField(max_length=255)),
                ('introduce', models.TextField()),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
