# Generated by Django 4.1 on 2023-02-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_company_government_governmentcontact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='authentication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'authentication',
            },
        ),
    ]
