# Generated by Django 4.1 on 2023-02-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_company_introduce'),
    ]

    operations = [
        migrations.DeleteModel(
            name='authentication',
        ),
    ]
